package theme

import (
	"slices"
	"strings"
)

type Theme interface {
	BackgroundColor() string
	MainColor() string
	CaretColor() string
	SubColor() string
	SubAltColor() string
	TextColor() string
	ErrorColor() string
	ErrorExtraColor() string
	ColorfulErrorColor() string
	ColorfulErrorExtraColor() string

	Init()
}

var staticPresets = []string{
    "8008",
    "80s_after_dark",
    "9009",
    "aether",
    "alduin",
    "alpine",
    "anti_hero",
    "arch",
    "beach",
    "bento",
    "bingsu",
    "bliss",
    "blue_dolphin",
    "blueberry_dark",
    "blueberry_light",
    "botanical",
    "breeze",
    "bushido",
    "cafe",
    "camping",
    "carbon",
    "catppuccin",
    "chaos_theory",
    "cherry_blossom",
    "comfy",
    "copper",
    "creamsicle",
    "cy_red",
    "cyberspace",
    "dark",
    "dark_magic_girl",
    "darling",
    "deku",
    "desert_oasis",
    "dev",
    "diner",
    "dino",
    "discord",
    "dmg",
    "dollar",
    "dots",
    "dracula",
    "drowning",
    "dualshot",
    "earthsong",
    "everblush",
    "evil_eye",
    "ez_mode",
    "fledgling",
    "fleuriste",
    "froyo",
    "frozen_llama",
    "fruit_chew",
    "fundamentals",
    "fruture_funk",
    "godspeed",
    "garen",
    "grand_prix",
    "gruvbox_dark",
    "gruvbox_light",
    "hammerhead",
    "hanok",
    "hedge",
    "honey",
    "horizon",
    "husqy",
    "iceberg_dark",
    "iceberg_light",
    "incognito",
    "ishtar",
    "iv_clover",
    "iv_spade",
    "joker",
    "laser",
    "lavender",
    "leather",
    "lil_dragon",
    "lime",
    "luna",
    "macroblank",
    "magic_girl",
    "mashu",
    "matcha_mocca",
    "material",
    "matrix",
    "menthol",
    "metaverse",
    "metropolis",
    "mexican",
    "miami",
    "miami_nights",
    "midnight",
    "milkshake",
    "mint",
    "mizu",
    "modern_dolch",
    "modern_dolch_light",
    "modern_ink",
    "monokai",
    "moonlight",
    "mountain",
    "mr_sleeves",
    "ms_cupcakes",
    "muted",
    "nautilus",
    "nebula",
    "night_runner",
    "nord",
    "nord_light",
    "norse",
    "oblivion",
    "olive",
    "olivia",
    "onedark",
    "our_theme",
    "paper",
    "passion_fruit",
    "peach_blossom",
    "peaches",
    "pink_lemondade",
    "pulse",
    "purpleish",
    "red_dragon",
    "red_samurai",
    "repose_dark",
    "repose_light",
    "retro",
    "retrocast",
    "rose_pine",
    "rose_pine_dawn",
    "rose_pine_moon",
    "rudy",
    "ryujinscales",
    "sreika",
    "serika_dark",
    "sewing_tin",
    "sewing_tin_light",
    "shoko",
    "slambook",
    "snes",
    "soaring_skies",
    "solarized_dark",
    "solarized_light",
    "sonokai",
    "stealth",
    "strawberry",
    "striker",
    "supersuser",
    "sweden",
    "tangerine",
    "taro",
    "terminal",
    "terra",
    "terror_below",
    "tiramisu",
    "trackday",
    "tron_orange",
    "vaporwave",
    "viridescent",
    "voc",
    "vscode",
    "watermelon",
    "wavez",
    "witch_girl",
}

func GetTheme(themeName string) Theme {
	if slices.Contains(staticPresets, strings.ToLower(themeName)) {
		return GetStaticTheme(themeName)
	}

    return GetStaticTheme("serika_dark")
}
